export type PetSpecies = 'perro' | 'gato' | 'otro';
export type PetSex = 'macho' | 'hembra';

export interface PetWeightEntry {
  id: string;
  date: string;
  weightKg: number;
  notes?: string;
}

export interface Pet {
  id: string;
  name: string;
  species: PetSpecies;
  breed: string;
  birthDate: string; // YYYY-MM-DD
  sex: PetSex;
  weightKg: number;
  color: string;
  microchipNumber: string; // e.g. 941000028471923 (15 digits ISO standard in Spain)
  microchipRegistry?: string; // REIAC / RIAC Madrid / etc.
  isSterilized: boolean;
  sterilizationDate?: string;
  vetClinicName: string;
  vetDoctorName?: string;
  vetPhone?: string;
  vetAddress?: string;
  insuranceCompany?: string; // e.g. Santalucía, Mapfre, Barkibu, Caser
  insurancePolicyNumber?: string;
  insuranceRenewalDate?: string;
  hasMandatoryCivilInsurance?: boolean;
  photoUrl: string;
  notes?: string;
  community: string; // e.g. Comunidad de Madrid, Cataluña, Andalucía, etc.
}

export type HealthRecordCategory =
  | 'vacuna'
  | 'desparasitacion_interna'
  | 'desparasitacion_externa'
  | 'medicamento'
  | 'alergia'
  | 'enfermedad'
  | 'consulta'
  | 'analisis'
  | 'intervencion'
  | 'peso'
  | 'nota_vet';

export interface HealthRecord {
  id: string;
  petId: string;
  category: HealthRecordCategory;
  title: string;
  date: string;
  dueDate?: string; // Next due date if applicable (e.g. revaccination)
  vetName?: string;
  clinic?: string;
  batchNumber?: string; // Lote de vacuna o medicamento
  notes?: string;
  status?: 'completado' | 'pendiente' | 'activo' | 'caducado';
  attachments?: string[]; // IDs or URLs
  severity?: 'leve' | 'moderada' | 'grave'; // For allergies/conditions
}

export interface Medication {
  id: string;
  petId: string;
  name: string;
  dosage: string; // e.g. "1 comprimido (50mg)"
  frequency: string; // e.g. "Cada 12 horas con comida"
  frequencyHours?: number; // e.g. 12
  startDate: string; // YYYY-MM-DD
  endDate: string; // YYYY-MM-DD
  instructions: string;
  prescribedByVet?: string;
  isActive: boolean;
  timesOfDay: string[]; // e.g. ["08:00", "20:00"]
  reminderEnabled: boolean;
  totalDosesTarget?: number;
  dosesGivenCount?: number;
}

export interface DoseLog {
  id: string;
  petId: string;
  medicationId: string;
  medicationName: string;
  dosage: string;
  timestamp: string; // ISO string
  administeredBy: string; // e.g. "María (Propietaria)" or "Carlos (Paseador)"
  notes?: string;
}

export type EventCategory =
  | 'veterinario'
  | 'vacunacion'
  | 'peluqueria'
  | 'desparasitacion'
  | 'paseo'
  | 'educacion'
  | 'guarderia'
  | 'seguro'
  | 'medicamento'
  | 'otro';

export interface CalendarEvent {
  id: string;
  petId: string;
  title: string;
  category: EventCategory;
  date: string; // YYYY-MM-DD
  time?: string; // HH:mm
  endTime?: string;
  location?: string;
  notes?: string;
  reminderBeforeMinutes?: number; // e.g. 60, 1440 (1 day)
  isCompleted?: boolean;
}

export type DocumentCategory =
  | 'cartilla_vacunacion'
  | 'informe_veterinario'
  | 'receta'
  | 'analisis'
  | 'analisis_lab'
  | 'seguro'
  | 'identificacion_microchip'
  | 'factura'
  | 'factura_veterinaria'
  | 'pasaporte_dni'
  | 'pasaporte_europeo'
  | 'otro';

export interface DocumentItem {
  id: string;
  petId: string;
  title: string;
  category: DocumentCategory;
  date?: string;
  uploadDate: string;
  fileSize?: string;
  fileType: 'pdf' | 'image' | 'doc';
  fileUrl?: string;
  thumbnailUrl?: string;
  notes?: string;
  clinic?: string;
  totalAmountEur?: number;
  extractedAiSummary?: string;
  tags?: string[];
}

export type PetDocument = DocumentItem;

export interface AiChatMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: string;
}

export interface Reminder {
  id: string;
  petId: string;
  title: string;
  category: EventCategory;
  dueDate: string; // YYYY-MM-DD
  dueTime?: string;
  frequency: 'una_vez' | 'diario' | 'semanal' | 'mensual' | 'trimestral' | 'anual';
  isAutoGenerated: boolean; // Generated by smart system (e.g. mandatory rabies vaccine, deworming)
  reasonSpanishLaw?: string; // Legal or veterinary basis (e.g. "Obligatorio según normativa de la Comunidad de Madrid")
  isCompleted: boolean;
  priority: 'alta' | 'media' | 'baja';
}

export type FamilyRole = 'propietario' | 'familiar' | 'cuidador' | 'veterinario';

export interface FamilyMember {
  id: string;
  name: string;
  email: string;
  role: FamilyRole;
  avatarUrl?: string;
  phone?: string;
  canEditHealth: boolean;
  canGiveMeds: boolean;
  status: 'activo' | 'invitacion_pendiente';
}

export interface ActivityLog {
  id: string;
  petId: string;
  userName: string;
  userRole: FamilyRole;
  actionType: 'medicamento' | 'paseo' | 'comida' | 'peso' | 'cita' | 'documento' | 'nota';
  description: string;
  timestamp: string; // ISO string
}

export type PlanTier = 'free' | 'pro';

export interface AuthUser {
  id: string;
  name: string;
  email: string;
  plan: PlanTier;
  createdAt?: string;
}

export interface UserProfile {
  id: string;
  name: string;
  email: string;
  phone?: string;
  community: string; // Spanish autonomous community
  plan: PlanTier;
  pushNotificationsEnabled: boolean;
  emailNotificationsEnabled: boolean;
  smsNotificationsEnabled: boolean;
}

export interface SpanishRegulationInfo {
  community: string;
  rabiesMandatory: boolean;
  rabiesFrequencyYears: number; // 1 or 2
  civilLiabilityInsuranceMandatory: boolean; // Mandatory for all dogs under Ley 7/2023
  microchipMandatory: boolean;
  dangerousBreedsSpecialReg: boolean;
  notes: string;
}
